formatting

diff --git a/ssm b/ssm
--- a/ssm
+++ b/ssm
@@ -9,7 +9,7 @@ SCRIPT_SOURCE="$BASH_SOURCE"
     DESC=${DESC:='Script Resources for ssm on macOS'}
     USAGE="source ${NAME:-} [help|test|usage|version]"
 #* ######################## initialization
-    source $(which ssm_usage)
+    # source $(which ssm_usage)
     source $(which ssm_resources)
     export SET_DEBUG=0        # set to 1 for verbose testing
     export SSM_LOADED=1       # prevent repeat loading
@@ -25,112 +25,79 @@ get_function_list() {
     }
 
 #* ######################## program debugging / logging functions
-# log_toggle() {
-    #   usage: log_toggle [filename]
-    #   toggle on and off logging to file
-    #       parameter
-    #           filename    - name of new logfile (default LOGFILE)
-    #       variable $LOG stores state
-    #       variable $LOGFILE stores filename
-    #   reference: https://unix.stackexchange.com/questions/80988/how-to-stop-redirection-in-bash
 
-    # set default log filename or $1
-    # # TODO this function is generating sporadic errors ...
-    # return 0
-    # if [[ -z "$1" ]]; then
-    #     if [[ -z "$LOG_FILE_NAME" ]]; then
-    #         LOG_FILE_NAME="${script_source:-'./'}LOGFILE.log"
-    #     fi
-    # else
-    #     LOG_FILE_NAME="${1}"
-    # fi
-    # touch "$LOG_FILE_NAME"
-    # # if log is on, turn it off
-    # if [[ "$LOG" == '1' ]]; then
-    #     LOG='0'
-    #     exec 1>&4- 2>&5-
-    #     attn "logging off ..."
-    # else # if it is off ... turn it on
-    #     LOG='1'
-    #     exec 4>&1 5>&2
-    #     # log to the filename stored in $LOG_FILE_NAME
-    #     db_echo "\${LOG_FILE_NAME}: ${LOG_FILE_NAME}"
-    #     exec > >(tee -a -i "${LOG_FILE_NAME}") 2>&1
-    #     attn "logging on ..."
-    # fi
-    # }
-test_echo() {
-    # log the current value of a given variable ($1)
-    # usage: test_echo <test name> <test code>
-    # report test results if:
-    #    - SET_DEBUG is set to '1' or cli [test] option set
-    #    - use log_toggle() to include file logging
-    if [[ $SET_DEBUG == 1 ]] || [[ $1 == 'test' ]]; then
-        printf "%bFunction Test -> %bPID %s %b" "$MAIN" "$CANARY" "$$" "$GO"
-        printf '%(%Y-%m-%d)T' -1
-        printf "%b test name: %s\n%b" "$ATTN" "$1" "${RESET_FG:-}"
-        shift
-        eval "$@"
-        printf "%bResult = %s%b\n" "$COOL" "$?" "${RESET_FG:-}"
-    fi
-    }
-test_var() {
-    # usage: test_var <test variable>
-    # report test results if:
-    #    - SET_DEBUG is set to '1' or cli [test] option set
-    #    - use log_toggle() to include file logging
-    # reference:
-    #   indirect variables: https://wiki.bash-hackers.org/syntax/pe#indirection
-    #   bash printf: https://www.linuxjournal.com/content/bashs-built-printf-function
-    if [[ $SET_DEBUG == 1 ]] && [[ -n "$1" ]]; then
-        local testvar="${1}"
-        echo "\$testvar: $testvar"
-        echo "testvar: "testvar
-        # echo "testvar: " ${!testvar}
-        echo ''
-        printf "%bVariable Test -> %bPID %s %b" "$MAIN" "$CANARY" "$$" "$GO"
-        printf '%(%Y-%m-%d)T' -1
-        printf "%b %15s -%b %s %b\n" "$ATTN" "\$$testvar" "$WARN" "$testvar" "$RESET_FG"
-    fi
-    }
-log_flag() { rain "#? ############################################################################"; }
+# test_echo() {
+#     # log the current value of a given variable ($1)
+#     # usage: test_echo <test name> <test code>
+#     # report test results if:
+#     #    - SET_DEBUG is set to '1' or cli [test] option set
+#     #    - use log_toggle() to include file logging
+#     if [[ $SET_DEBUG == 1 ]] || [[ $1 == 'test' ]]; then
+#         printf "%bFunction Test -> %bPID %s %b" "$MAIN" "$CANARY" "$$" "$GO"
+#         printf '%(%Y-%m-%d)T' -1
+#         printf "%b test name: %s\n%b" "$ATTN" "$1" "${RESET_FG:-}"
+#         shift
+#         eval "$@"
+#         printf "%bResult = %s%b\n" "$COOL" "$?" "${RESET_FG:-}"
+#     fi
+#     }
+# test_var() {
+#     # usage: test_var <test variable>
+#     # report test results if:
+#     #    - SET_DEBUG is set to '1' or cli [test] option set
+#     #    - use log_toggle() to include file logging
+#     # reference:
+#     #   indirect variables: https://wiki.bash-hackers.org/syntax/pe#indirection
+#     #   bash printf: https://www.linuxjournal.com/content/bashs-built-printf-function
+#     if [[ $SET_DEBUG == 1 ]] && [[ -n "$1" ]]; then
+#         local testvar="${1}"
+#         echo "\$testvar: $testvar"
+#         echo "testvar: "testvar
+#         # echo "testvar: " ${!testvar}
+#         echo ''
+#         printf "%bVariable Test -> %bPID %s %b" "$MAIN" "$CANARY" "$$" "$GO"
+#         printf '%(%Y-%m-%d)T' -1
+#         printf "%b %15s -%b %s %b\n" "$ATTN" "\$$testvar" "$WARN" "$testvar" "$RESET_FG"
+#     fi
+#     }
+# log_flag() { rain "#? ############################################################################"; }
 
 #* ######################## error handling
-_set_traps() {
-    cur_opts="$-"
-    debug_opts="axET"
-    set "-${cur_opts}${debug_opts}"
-    }
+# _set_traps() {
+#     cur_opts="$-"
+#     debug_opts="axET"
+#     set "-${cur_opts}${debug_opts}"
+#     }
 
-_trap_error() {
-    me "ERR: $ERR"
-    set "-${cur_opts}"
-    # return 0
-    }
-_trap_debug() {
-    # return 0
-    ce "Script source:$MAIN $SCRIPT_SOURCE$RESET_FG $@ \n"
-    attn "echo VARIABLE ($VARIABLE) is being used here."
-    }
-_trap_exit() {
-    # https://stackoverflow.com/a/50270940/9878098
-    exitcode=$?
-    printf 'error executing script...\n' 1>&2
-    printf 'exit code returned: %s\n' "$exitcode"
-    printf 'the command executing at the time of the error was: %s\n' "$BASH_COMMAND"
-    printf 'command present on line: %d' "${BASH_LINENO[0]}"
-    # Some more clean up code can be added here before exiting
-    set "-${cur_opts}"
-    exec 4>&- 5>&- 6>&-
-    if [[ "$LOG" == '1' ]]; then
-        LOG='0'
-        exec 1>&4 2>&5
-        exec 4>&- 5>&-
-        attn "logging off ..."
-    fi
+# _trap_error() {
+#     me "ERR: $ERR"
+#     set "-${cur_opts}"
+#     # return 0
+#     }
+# _trap_debug() {
+#     # return 0
+#     ce "Script source:$MAIN $SCRIPT_SOURCE$RESET_FG $@ \n"
+#     attn "echo VARIABLE ($VARIABLE) is being used here."
+#     }
+# _trap_exit() {
+#     # https://stackoverflow.com/a/50270940/9878098
+#     exitcode=$?
+#     printf 'error executing script...\n' 1>&2
+#     printf 'exit code returned: %s\n' "$exitcode"
+#     printf 'the command executing at the time of the error was: %s\n' "$BASH_COMMAND"
+#     printf 'command present on line: %d' "${BASH_LINENO[0]}"
+#     # Some more clean up code can be added here before exiting
+#     set "-${cur_opts}"
+#     exec 4>&- 5>&- 6>&-
+#     if [[ "$LOG" == '1' ]]; then
+#         LOG='0'
+#         exec 1>&4 2>&5
+#         exec 4>&- 5>&-
+#         attn "logging off ..."
+#     fi
 
-    exit $exitcode
-    }
+#     exit $exitcode
+#     }
 #* ######################## script tests
 _run_tests() {
     _run_debug_config() {
@@ -189,28 +156,28 @@ _run_tests() {
         unset LOG
         }
     
-    # db_echo "zsh 'BASH_SOURCE': ${(%):-%N}"
-    db_echo "BASH_SOURCE: $BASH_SOURCE"
-    db_echo "\$0: $0"
-    db_echo "\$1: $1"
-    ce "Script source:${MAIN} ${SCRIPT_SOURCE}$RESET_FG"
-    # echo ${filename##*/}
-    # lime "zsh 'BASH_SOURCE': ${(%):-%N}"
-    # lime "(%): ${%N}"
-    db_echo "\nTesting script ${NAME} version ${VERSION}."
-    ce "Script source:$MAIN ${SCRIPT_SOURCE[0]##*/}${RESET_FG:-}\n"
-    ce "Script parent:$MAIN ${SCRIPT_SOURCE[1]##*/}${RESET_FG:-}\n"
-    ce "Script grandparent:$MAIN ${SCRIPT_SOURCE[2]##*/}${RESET_FG:-}\n"
-    _run_debug_config
-    _bt_color_sample_test
-    _test_standard_script_modules
-    return 0
+    # # db_echo "zsh 'BASH_SOURCE': ${(%):-%N}"
+    # db_echo "BASH_SOURCE: $BASH_SOURCE"
+    # db_echo "\$0: $0"
+    # db_echo "\$1: $1"
+    # ce "Script source:${MAIN} ${SCRIPT_SOURCE}$RESET_FG"
+    # # echo ${filename##*/}
+    # # lime "zsh 'BASH_SOURCE': ${(%):-%N}"
+    # # lime "(%): ${%N}"
+    # db_echo "\nTesting script ${NAME} version ${VERSION}."
+    # ce "Script source:$MAIN ${SCRIPT_SOURCE[0]##*/}${RESET_FG:-}\n"
+    # ce "Script parent:$MAIN ${SCRIPT_SOURCE[1]##*/}${RESET_FG:-}\n"
+    # ce "Script grandparent:$MAIN ${SCRIPT_SOURCE[2]##*/}${RESET_FG:-}\n"
+    # _run_debug_config
+    # _bt_color_sample_test
+    # _test_standard_script_modules
+    # return 0
     }
 #! ######################## main loop
 _main_loop() {
     script_name=$NAME
     set_man_page
-    pgrep -fl "$BASH_SOURCE"
+    # pgrep -fl "$BASH_SOURCE"
 
     # trap _trap_error ERR
     # trap _trap_exit EXIT
